name: Monitorar Status dos Serviços BR

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  check-status:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: |
        echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
        echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> $GITHUB_ENV

    - name: Check service status
      env:
        SUPABASE_URL: ${{ env.SUPABASE_URL }}
        SUPABASE_KEY: ${{ env.SUPABASE_KEY }}
      run: |
        SERVICES=("discord" "zoom" "teams" "slack" "google" "outlook" "chatgpt" "linkedin")
        
        for SERVICE in "${SERVICES[@]}"; do
          case "$SERVICE" in
            "discord")
              URL="https://discord.com"
              SERVICE_CAP="Discord"
              ;;
            "zoom")
              URL="https://zoom.us"
              SERVICE_CAP="Zoom"
              ;;
            "teams")
              URL="https://teams.microsoft.com"
              SERVICE_CAP="Teams"
              ;;
            "slack")
              URL="https://slack.com"
              SERVICE_CAP="Slack"
              ;;
            "google")
              URL="https://www.google.com"
              SERVICE_CAP="Google"
              ;;
            "outlook")
              URL="https://outlook.live.com"
              SERVICE_CAP="Outlook"
              ;;
            "chatgpt")
              URL="https://chat.openai.com"
              SERVICE_CAP="ChatGPT"
              ;;
            "linkedin")
              URL="https://www.linkedin.com"
              SERVICE_CAP="LinkedIn"
              ;;
            *)
              URL="https://www.$SERVICE.com.br"
              SERVICE_CAP="$(tr '[:lower:]' '[:upper:]' <<< ${SERVICE:0:1})${SERVICE:1}"
              ;;
          esac

          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          if [ "$STATUS_CODE" -eq 200 ]; then
            STATUS="true"
          else
            STATUS="false"
          fi

          SERVICE_URL=$(echo "$SERVICE_CAP" | sed 's/ /%20/g')

          curl -s -X PATCH "$SUPABASE_URL/rest/v1/status_apps?nome=eq.$SERVICE_URL" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"status\": $STATUS, \"ultima_verificacao\": \"$(date -u +%FT%TZ)\"}" > /dev/null

          echo "Atualizado ${SERVICE_CAP}: $STATUS (HTTP code: $STATUS_CODE)"
        done
