            name: Monitorar Status dos Apps BR

on:
  schedule:
    - cron: '*/2 * * * *'  # Executa a cada 2 minutos
workflow_dispatch:
jobs:
  check-services:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar status do WhatsApp
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}  # Sua service key do Supabase
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://web.whatsapp.com")
          if [ "$STATUS_CODE" -eq 200 ]; then
            STATUS="true"
          else
            STATUS="false"
          fi
          curl -X PATCH "https://zyscwlksespdrpnrifzm.supabase.co/rest/v1/status_apps?nome=eq.WhatsApp" \
            -H "apikey: $eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5c2N3bGtzZXNwZHJwbnJpZnptIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTU0MTg5NSwiZXhwIjoyMDU1MTE3ODk1fQ.0iNohKohK1XK_JvBg4b8N3ZBnCLndUlExaH_QUlnNbs" \
            -H "Content-Type: application/json" \
            -d '{"status": '$STATUS'}'

      - name: Verificar status do iFood
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}  
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://www.ifood.com.br")
          if [ "$STATUS_CODE" -eq 200 ]; then
            STATUS="true"
          else
            STATUS="false"
          fi
          curl -X PATCH "https://SEU_SUPABASE_ID.supabase.co/rest/v1/status_apps?nome=eq.iFood" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -d '{"status": '$STATUS'}'

      - name: Verificar status do Nubank
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}  
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" "https://nubank.com.br")
          if [ "$STATUS_CODE" -eq 200 ]; then
            STATUS="true"
          else
            STATUS="false"
          fi
          curl -X PATCH "https://SEU_SUPABASE_ID.supabase.co/rest/v1/status_apps?nome=eq.Nubank" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Content-Type: application/json" \
            -d '{"status": '$STATUS'}'

